version: '1.0'
stages:
  - "prepare"
  - "build"
  - "store"
  - "deploy"
steps:
  clone:
    title: "Cloning repo"
    stage: "prepare"
    type: git-clone
    repo: "Kirems/helm-sample-app"
    revision: "${{CF_BRANCH}}"
    git: "github-2"
  build:
    title: "Building Docker Image"
    stage: "build"
    type: "build"
    working_directory: ./helm-sample-app
    image_name: "kiro/helm-go-example"
    tag: 2.0.0
    dockerfile: "Dockerfile"
  store:
    title: "Storing Helm Chart"
    type: "helm"
    stage: "store"
    working_directory: ./helm-sample-app
    arguments:
      action: "push"
      helm_version: 3.0.2
      chart_name: "charts/helm-example"
      helm_repository_context: "${{HELM_REPO}}"
  deploy:
    type: "helm"
    stage: "deploy"
    working_directory: ./helm-sample-app
    arguments:
      action: "install"
      chart_name: "charts/helm-example"
      release_name: "my-go-chart-prod"
      helm_version: 3.0.2
      kube_context: "${{KUBE_CLUSTER_NAME}}"
      custom_values:
        - 'buildID=${{CF_BUILD_ID}}'
        - 'image_pullPolicy=Always'
        - 'image_tag=2.0.0'
        - 'replicaCount=3'
