apiVersion: v1
kind: ConfigMap
metadata:
  name: react-ui-config
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "ui.labels" . | nindent 4 }}
data:
  .env: REACT_APP_NAME=DEFAULT
  