apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.app.namespace }}
  name: react-ui-dep
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        {{- include "ui.labels" . | nindent 8 }}
    spec:
      containers:
        - name: react-ui
          image: "{{ .Values.app.container.image.repository }}:{{ .Values.app.container.image.tag }}"
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/env.js
              subPath: production-env.js
          imagePullPolicy: IfNotPresent
          resources:
            {{- toYaml .Values.app.computerc | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: app-config
