apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.app.namespace }}
  name: ui-service
  labels:
  {{- include "ui.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: react-ui
  