app:
  replicas: 3
  env: prod
  namespace: prod
  container:
    image:
      repository: "168658707614.dkr.ecr.eu-west-2.amazonaws.com/kiro"
      tag: "{{BUILD_NUM}}"
  computerc:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 1
      memory: 1Gi


