app:
  replicas: 1
  env: dev
  namespace: dev
  container:
    image: 
      repository: "168658707614.dkr.ecr.eu-west-2.amazonaws.com/kiro"
      tag: "helm-go-example2.0.0"
  computerc:
    limits:
      cpu: 0.2
      memory: 500Mi
    requests:
      cpu: 0.2
      memory: 500Mi

hpa:
  enabled: false


config:
  name: config.yaml
  data: 
    timeout: 10s
    logfile: /app/var/log.txt
    database:
      ip: 10.20.30.20
      name: ui-dev 


configxml:
  name: app.xml 